### ISSUE TITLE
Issue with Sumo Logic CircleCI Insights orb and manual approval steps in workflow

### ISSUE THREAD

**Issue by ababra-rbc** [CircleCI-Public/sumologic-orb#30]
### Orb version
1.1.0

### What happened
We are using the `circleci/sumologic` orb (latest version) to forward CircleCI-related metrics to Sumo Logic, as [outlined here ](https://circleci.com/docs/2.0/insights/#sumo-logic-integration).

Discovered an issue with the `sumologic/workflow-collector`: if a CircleCI workflow has a manual approval step, the workflow collector will gracefully terminate and not resume once approval is granted - as a result we will lose metrics for the rest of the workflow run.

Is there any way to re-trigger the workflow collector to run after approval has been granted, or any other workaround/solution? Thanks.

### Expected behavior
Re-trigger the workflow collector to run after approval has been granted.

**Comment by KyleTryon** [comment]
Hello @ababra-rbc, 

This was an intentional "feature" put in place to correct for a different issue and thus was made to be expected that the Sumo-Logic orb does not support on-hold jobs.

**Why?**
  This is a complex question actually but, it's due to limitations in how orbs operate and how this orb is used to attempt to emulate a webhook that fires at the end of a pipeline.

Currently, there is no way to run a task at the end of a pipeline on CircleCI, or send a webhook with some payload after a pipeline has finished. What this orb is doing is creating a job which runs alongside your workflow and waits for it to finish. If a workflow goes on-hold, it may do so for up to 30 days, but a job on CircleCI may only run for up to 5 hours. After 5 hours a job will exit in failure.

So, if on-hold was ignored by this orb, the side-car job which is waiting for the workflow to finish may wait up to 5 hours (spending CircleCI credits the whole time as well) and then fail, which means no data at all would be sent from the workflow.

By exiting at on-hold jobs, we can ensure to capture at least partial information.

**How will we fix this?**

Webhooks are coming to CircleCI. In the not-so-distant future, you will be able to define where to send webhooks for a workflow and send this data/event to services without the use of an orb. Orbs may still be used to supplement data but the bulk of activity will be replaced by webhooks.
